CREATE TABLE "user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100),
  "slug" varchar(50),
  "email" varchar UNIQUE,
  "bio" text,
  "created_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "tweet" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content" varchar(150),
  "user_id" int,
  "created_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "follower" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "follower_id" int,
  "followed_id" int,
  "created_at" timestamp DEFAULT 'now()'
);

ALTER TABLE "tweet" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "follower" ADD FOREIGN KEY ("follower_id") REFERENCES "user" ("id");

ALTER TABLE "follower" ADD FOREIGN KEY ("followed_id") REFERENCES "user" ("id");