CREATE TYPE "product_status" AS ENUM (
  'in_stock',
  'out_of_stock',
  'running_low'
);

CREATE TYPE "order_status" AS ENUM (
  'placed',
  'confirm',
  'processed',
  'completed'
);

CREATE TABLE "product" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "serial" varchar,
  "name" varchar(200),
  "merchant" int,
  "price" "float(10, 4)",
  "status" product_status,
  "stock" int,
  "created_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "merchant" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "country" int,
  "created_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "country" (
  "id" SERIAL PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "order" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "status" order_status,
  "user_id" int,
  "quantity" int,
  "total" "float(12, 2)",
  "created_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "order_item" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int,
  "product_id" int,
  "quantity" int
);

ALTER TABLE "product" ADD FOREIGN KEY ("merchant") REFERENCES "merchant" ("id");

ALTER TABLE "merchant" ADD FOREIGN KEY ("country") REFERENCES "country" ("id");

ALTER TABLE "order_item" ADD FOREIGN KEY ("order_id") REFERENCES "order" ("id");

ALTER TABLE "order_item" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id");