-- VIEW IN THIS LESSON 
-- 1. CREATE TABLE
-- 2. INSERT DATA
-- 3. UPDATE DATA
-- 4. DELETE, TRUNCATE AND DROP TABLE
-- 5. USE WHERE AND LIKE CLAUSES


-- CREATE TABLE
CREATE TABLE users (
	name VARCHAR(100) UNIQUE
);

auto commit; -- DEACTIVATE AUTO-COMMIT FOR NOT GET ERROR IN DB

-- INSERT DATA IN TABLE
INSERT INTO users (name) VALUES('Cartógenes');


-- UPDATE DATA IN TABLE
UPDATE users SET name = 'Prisciliano Cortés' WHERE name = 'Prisciliano';

-- SELECT TABLE
SELECT * FROM users;

-- SELECT TABLE WITH LIMIT
SELECT * FROM users LIMIT 2;

-- SELECT TABLE WITH LIMIT AND SKIP THE TWO LIMIT RECORDS AND OFFSET
SELECT * FROM users LIMIT 2 OFFSET 2;

-- SELECT TABLE WHERE CLAUSE
SELECT * FROM users WHERE name = 'Lidia';

-- SELECT TABLE WHERE CLAUSE WITH FILTER DATA LIKE STATEMENTS
SELECT * FROM users WHERE name LIKE '%ia';
SELECT * FROM users WHERE name LIKE 'Ca%';

-- DELETE DATA FROM TABLE
DELETE FROM users WHERE name = 'Cartógenes';

-- DELETE ALL REGISTER TABLE - DO NOT TO THIS
DELETE FROM users;

-- DELETE THE TABLE WITH ITS RECORDS
DROP TABLE users;

-- DELETE RECORDS FROM THE TABLE
TRUNCATE TABLE users;