-- PRIMARY KEY WITH UUID

-- SELECT AND VERIFY EXIST UUID IN BD
SELECT gen_random_uuid();

-- IF NOT EXIT, INSTALL PACKAGE EXTENSION
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- SELECT AND VERIFY EXIST UUID IN BD
SELECT uuid_generate_v4();

-- DROP PACKAGE EXTENSION
DROP EXTENSION "uuid-ossp";

-- CREATE TABLE WITH UUID
CREATE TABLE users5 (
	"user_id" UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
	"username" VARCHAR
)